services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn real_time_detection.asgi:application --host=0.0.0.0 --port=$PORT"
    environment:
      - name: PYTHON_VERSION
        value: "3.9"  # Or your desired Python version
