services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn real_time_detection.wsgi:application --bind 0.0.0.0:$PORT"
    environment:
      - name: PYTHON_VERSION
        value: "3.9"  # Or your desired Python version
